# Generated by Django 3.1.7 on 2021-03-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='role',
            field=models.ForeignKey(default='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.roles'),
        ),
    ]
