# Generated by Django 3.1.5 on 2021-01-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.CharField(max_length=5)),
                ('currencyDes', models.CharField(max_length=40, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classDescription', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('createDate', models.DateTimeField()),
                ('modifiedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('categoryDescription', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('createDate', models.DateTimeField()),
                ('modifiedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
                ('productClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productclass')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prodDescription', models.CharField(max_length=500)),
                ('MRP', models.FloatField()),
                ('sellingPrice', models.FloatField()),
                ('isDiscountAvailable', models.BooleanField(default=False)),
                ('discountPercentage', models.IntegerField(default=0)),
                ('isProductAvailable', models.BooleanField(default=True)),
                ('isStockAvailabe', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('productcol', models.CharField(blank=True, max_length=3, null=True)),
                ('productcol1', models.CharField(blank=True, max_length=50, null=True)),
                ('batchNumber', models.CharField(max_length=50)),
                ('productcol2', models.CharField(blank=True, max_length=50, null=True)),
                ('manufactureDate', models.DateTimeField()),
                ('expiryDate', models.DateTimeField()),
                ('createdBy', models.CharField(max_length=200)),
                ('createDate', models.DateTimeField()),
                ('modifiedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.currency')),
                ('prodCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory')),
            ],
        ),
    ]
