# Generated by Django 3.1.7 on 2021-03-29 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(default='Generic', max_length=500)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('createDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modifiedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaxType', models.CharField(blank=True, choices=[('GST', 'GST'), ('VAT', 'VAT')], default='GST', max_length=4, null=True)),
                ('TaxPercentage', models.IntegerField(default=0, max_length=2)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('createDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modifiedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productSpecification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productcol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.tax'),
        ),
    ]
