# Generated by Django 3.1.7 on 2021-03-31 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210329_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 20, 35, 40, 119563)),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='createdBy',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
