# Generated by Django 3.1.7 on 2021-03-31 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210329_1525'),
        ('product', '0005_auto_20210331_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 20, 38, 24, 913534)),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.siteusers'),
        ),
    ]
