# Generated by Django 3.1.7 on 2021-04-02 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210329_1525'),
        ('product', '0006_auto_20210331_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 14, 50, 37, 65984)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.siteusers'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 14, 50, 37, 64987)),
        ),
    ]
