# Generated by Django 3.1.7 on 2021-04-13 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210329_1525'),
        ('product', '0007_auto_20210402_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productcol',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productcol1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productcol2',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='batchNumber',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 18, 36, 46, 469244)),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.siteusers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactureDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productSpecification',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.tax'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 18, 36, 46, 469244)),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 18, 36, 46, 469244)),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductImageLocation', models.CharField(max_length=500)),
                ('IsPrimaryImage', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('createDate', models.DateTimeField()),
                ('modifiedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcol', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
