# Generated by Django 3.1.7 on 2021-04-13 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210413_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 19, 43, 2, 356449)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 19, 43, 2, 354462)),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 19, 43, 2, 354462)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='TaxType',
            field=models.CharField(blank=True, choices=[('NOTAX', 'NoTax'), ('GST', 'GST'), ('VAT', 'VAT')], default='GST', max_length=10, null=True),
        ),
    ]
