# Generated by Django 3.1.7 on 2021-04-14 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210413_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 14, 43, 41, 495981)),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiryDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 14, 43, 41, 493985)),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 14, 43, 41, 493985)),
        ),
    ]
