# Generated by Django 3.1.7 on 2021-03-22 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(max_length=50)),
                ('mihpayid', models.CharField(default='123456789', max_length=50)),
                ('status', models.CharField(default='success', max_length=50)),
                ('txnid', models.CharField(default='1000000', max_length=50)),
                ('bank_ref_num', models.CharField(blank=True, max_length=50, null=True)),
                ('bankcode', models.CharField(blank=True, max_length=50, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=50, null=True)),
                ('cardnum', models.CharField(blank=True, max_length=50, null=True)),
                ('payuMoneyId', models.CharField(default='1112263210', max_length=50)),
                ('net_amount_debit', models.FloatField(default=0.0, max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('paidDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysports.order')),
                ('paidBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.siteusers')),
            ],
            options={
                'db_table': 'Payment_Details',
            },
        ),
    ]
