# Generated by Django 3.1.7 on 2021-03-22 05:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(default='', max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('address3', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('total', models.CharField(max_length=10)),
                ('orderDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('orderedBy', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.siteusers')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('orderDate',),
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemQuantity', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sellingPrice', models.FloatField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysports.order')),
            ],
            options={
                'db_table': 'order_details',
                'ordering': ('created',),
            },
        ),
    ]
